#!/usr/bin/env python3
"""Exercise EVERY implemented route, including the ones that key the transmitter.

    tools/walk_all_routes.py <host:port>

⚠️ THIS TOOL FIRES STATE-CHANGING ROUTES. It will key PTT, change mode, switch
antennas and move the frequency. Against a real station that is exactly the
accident docs/internal/CARRYOVER.md section 9 records - a control-route probe that changed the
operating mode mid-session.

So it refuses to run unless the target PROVES it is a simulator:

    GET /api/backend  ->  {"simulated": true}

The reference .NET host does not serve that route at all, so it 404s there and
this tool refuses. Anything that is not an explicit simulated:true is a refusal -
a 404, a connection error, a missing field. It fails CLOSED.

There is deliberately no --force. An override would make the check advisory, and
an advisory check on something that keys a transmitter is not a check.
"""

import json
import sys
import urllib.request
import urllib.error

READ = [
    "/api/health", "/api/status", "/api/status/full", "/api/meters",
    "/api/freq", "/api/freq-b", "/api/ant/get", "/api/ant/rx/get",
    "/api/cw-speed/get", "/api/rf-gain/get", "/api/power/limit", "/api/test",
]

# Route -> the /api/status or /api/status/full field it should move, and the
# value expected afterwards. Checking the ROUTE'S OWN reply proves nothing: it
# is generated by the same handler that is under test. Reading the rig back is
# the only evidence the command actually did something.
DRIVE = [
    ("/api/mode/lsb",    "mode",   "LSB"),
    ("/api/mode/usb",    "mode",   "USB"),
    ("/api/mode/cw",     "mode",   "CW"),
    ("/api/power/qrp",   "power",  5),
    ("/api/power/high",  "power",  100),
    ("/api/split/on",    "split",  True),
    ("/api/split/off",   "split",  False),
    ("/api/vfo/b",       "vfo",    "B"),
    ("/api/vfo/a",       "vfo",    "A"),
    # ⚠️ TWO DIFFERENT LOCKS, and they are not interchangeable.
    # /api/lock/* is the RIG's own lock (CAT "LK"), reported as `lock` in
    # /api/status/full. /api/vfo-lock/* is a SOFTWARE lock the host keeps,
    # reported as `vfo_locked` in /api/status. Confirmed against the reference
    # host's BuildApiStatus, which reads vfo_locked from its config, not the rig.
    ("/api/lock/on",       "lock",       True),
    ("/api/lock/off",      "lock",       False),
    ("/api/vfo-lock/on",   "vfo_locked", True),
    ("/api/vfo-lock/off",  "vfo_locked", False),
    ("/api/diversity/on",  "diversity",  True),
    ("/api/diversity/off", "diversity",  False),
    ("/api/nb/on",       "nb",     True),
    ("/api/nb/off",      "nb",     False),
    ("/api/nr/on",       "nr",     True),
    ("/api/nr/off",      "nr",     False),
    ("/api/notch/on",    "notch",  True),
    ("/api/notch/off",   "notch",  False),
    ("/api/att/on",      "att",    True),
    ("/api/att/off",     "att",    False),
    ("/api/vox/on",      "vox",    True),
    ("/api/vox/off",     "vox",    False),
    ("/api/comp/on",     "comp",   True),
    ("/api/comp/off",    "comp",   False),
    ("/api/mon/on",      "mon",    True),
    ("/api/mon/off",     "mon",    False),
    ("/api/rit/on",      "rit",    True),
    ("/api/rit/off",     "rit",    False),
    ("/api/xit/on",      "xit",    True),
    ("/api/xit/off",     "xit",    False),
    ("/api/agc/fast",    "agc",    "FAST"),
    ("/api/agc/slow",    "agc",    "SLOW"),
    ("/api/agc/auto",    "agc",    "AUTO"),
    ("/api/ant/2",       "ant",    2),
    ("/api/ant/1",       "ant",    1),
    ("/api/preamp/on",   "preamp", 1),
    ("/api/preamp/off",  "preamp", 0),
    ("/api/ant/rx/on",   "rxant",  True),
    ("/api/ant/rx/off",  "rxant",  False),
    ("/api/ptt/on",      "tx",     True),

    # Prefix routes - the parameterised half of the surface, and the half a
    # panel actually uses: band buttons, the keypad, the numeric setters.
    ("/api/band/20",           "freq", 14200000),
    ("/api/band/40",           "freq", 7200000),
    ("/api/freq/set/14074000", "freq", 14074000),
    ("/api/mode/lsb",          "mode", "LSB"),
    # ⚠️ 49, not 50, and that is CORRECT. Percent -> raw -> percent is lossy in
    # integer math: 50*255/100 = 127, and 127*100/255 = 49. The reference host
    # does the same arithmetic and reports the same 49, so matching it matters
    # more than a round number. A client showing a slider should send percent and
    # trust the readback, not assume it gets its own value returned.
    ("/api/volume/set/50",     "af_gain_pct", 49),
    ("/api/power/set/25",      "power", 25),
    ("/api/cw-speed/set/25",   "cw_speed", 25),
]

# Reachable, but with no field to read back - asserted only to answer 200.
SMOKE_PREFIX = [
    "/api/step/1000/up", "/api/step/1000/down", "/api/rf-gain/set/60",
    "/api/memory/recall/3", "/api/ssb-out-level/set/40", "/api/remote-tx/gain/40",
    "/api/mode/usb", "/api/band/15",
]

# Routes that must answer honestly rather than 404 when a feature is absent.
HONEST_ABSENT = [
    "/api/rxant/2", "/api/preset/nonexistent", "/api/cw/memory/1",
    "/api/cw/send/TEST", "/api/voice/play/1", "/api/tune/tgxl", "/api/cw/status",
]

# Frequency-changing routes the software VFO lock MUST refuse.
VFO_LOCK_BLOCKED = [
    "/api/band/40", "/api/freq/set/14200000", "/api/freq/digit/7",
    "/api/step/1000/up", "/api/quick-split", "/api/freq/send",
    "/api/freq/clear", "/api/freq/backspace", "/api/vfo/swap",
]

SMOKE = [
    "/api/toggle/nb", "/api/toggle/nr", "/api/toggle/dnr", "/api/toggle/notch",
    "/api/toggle/lock", "/api/att/toggle", "/api/vox/toggle", "/api/comp/toggle",
    "/api/mon/toggle", "/api/rit/toggle", "/api/xit/toggle", "/api/nb/toggle",
    "/api/nr/toggle", "/api/notch/toggle", "/api/split/toggle", "/api/ant/toggle",
    "/api/ant/rx/toggle", "/api/lock/toggle", "/api/agc/cycle", "/api/preamp/cycle",
    "/api/width/narrow", "/api/width/medium", "/api/width/wide",
    "/api/rit/up", "/api/rit/down", "/api/rit/clear",
    "/api/cw-speed/up", "/api/cw-speed/down", "/api/vfo/swap",
    "/api/agc/off", "/api/agc/mid", "/api/power/low", "/api/power/mid",
    "/api/power/max", "/api/mode/am", "/api/mode/fm", "/api/mode/data",
    "/api/ant/3",
]


def get(base, path):
    try:
        with urllib.request.urlopen(f"http://{base}{path}", timeout=8) as r:
            return r.status, json.loads(r.read().decode())
    except urllib.error.HTTPError as e:
        return e.code, None
    except Exception as e:                                   # noqa: BLE001
        return 0, {"_error": str(e)}


def wait_for(base, src, field, expect, timeout=3.0):
    """Poll until `field` reads `expect`, or give up. Returns (value, seconds)."""
    import time
    t0 = time.time()
    actual = None
    while time.time() - t0 < timeout:
        _, body = get(base, src)
        actual = (body or {}).get(field)
        if actual == expect:
            return actual, time.time() - t0
        time.sleep(0.1)
    return actual, time.time() - t0


def require_simulator(base):
    status, body = get(base, "/api/backend")
    if status != 200 or not isinstance(body, dict) or body.get("simulated") is not True:
        sys.exit(
            f"REFUSING to walk {base}.\n"
            f"  /api/backend -> {status} {body}\n"
            "  This tool fires state-changing routes (PTT, mode, antenna). It runs\n"
            "  only against a host that proves simulated:true. There is no override."
        )
    print(f"  backend: {body['cat']} (simulated)\n")


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    base = sys.argv[1]
    require_simulator(base)

    failures = 0
    for path in READ:
        status, _ = get(base, path)
        if status != 200:
            print(f"  FAIL  {path}: {status}")
            failures += 1
    print(f"  read-only: {len(READ) - failures}/{len(READ)} answered 200")

    drive_fail = 0
    for path, field, expect in DRIVE:
        status, _ = get(base, path)
        if status != 200:
            print(f"  FAIL  {path}: {status}")
            drive_fail += 1
            continue
        # Wait for the value rather than sleeping a fixed guess: commands are
        # queued for the poller thread, so there is always some latency, and a
        # fixed sleep either flakes or wastes time. A bounded wait still fails
        # if the command never lands.
        if field == "af_gain_pct":
            actual, _ = wait_for(base, "/api/volume/get", "volume", expect)
            if actual != expect:
                print(f"  FAIL  {path}: volume is {actual!r}, expected {expect!r}")
                drive_fail += 1
            continue
        if field == "cw_speed":
            actual, _ = wait_for(base, "/api/cw-speed/get", "wpm", expect)
            if actual != expect:
                print(f"  FAIL  {path}: wpm is {actual!r}, expected {expect!r}")
                drive_fail += 1
            continue
        src = "/api/status" if field in (
            "mode", "power", "split", "vfo", "vfo_locked", "diversity", "tx",
            "freq") else "/api/status/full"
        actual, waited = wait_for(base, src, field, expect)
        if actual != expect:
            print(f"  FAIL  {path}: {field} is {actual!r}, expected {expect!r}")
            drive_fail += 1
    print(f"  drive:     {len(DRIVE) - drive_fail}/{len(DRIVE)} verified by reading the rig back")

    # The keypad, end to end: digits accumulate then tune the rig.
    keypad_fail = 0
    get(base, "/api/freq/clear")
    for d in "14250":
        st, b = get(base, f"/api/freq/digit/{d}")
        if st != 200:
            print(f"  FAIL  /api/freq/digit/{d}: {st}"); keypad_fail += 1
    st, b = get(base, "/api/freq/send")
    if (b or {}).get("freq_hz") != 14250000:
        print(f"  FAIL  /api/freq/send: {b}"); keypad_fail += 1
    else:
        actual, _ = wait_for(base, "/api/status", "freq", 14250000)
        if actual != 14250000:
            print(f"  FAIL  keypad did not reach the rig: {actual}"); keypad_fail += 1
    # A non-digit must be refused: the buffer is parsed as a number later, so a
    # stray character silently became 0 and tuned to the bottom of the range.
    # A refusal may come back as 4xx with no parsed body, so check the STATUS,
    # not the body - an earlier version read the body only and reported a pass
    # for a route that had correctly refused.
    st, b = get(base, "/api/freq/digit/x")
    refused = st >= 400 or (isinstance(b, dict) and b.get("status") == "error")
    if not refused:
        print(f"  FAIL  /api/freq/digit/x was accepted: {st} {b}"); keypad_fail += 1
    print(f"  keypad:    {'ok' if not keypad_fail else str(keypad_fail) + ' failure(s)'}")

    # ⚠️ The software VFO lock must REFUSE frequency changes, for every caller.
    lock_fail = 0
    get(base, "/api/vfo-lock/on")
    for path in VFO_LOCK_BLOCKED:
        st, b = get(base, path)
        if (b or {}).get("vfo_locked") is not True:
            print(f"  FAIL  {path} was NOT blocked by the VFO lock: {b}"); lock_fail += 1
    st, b = get(base, "/api/mode/usb")   # not a frequency change: must still work
    if (b or {}).get("status") != "ok":
        print(f"  FAIL  /api/mode/usb blocked by the VFO lock: {b}"); lock_fail += 1
    get(base, "/api/vfo-lock/off")
    st, b = get(base, "/api/band/40")
    if (b or {}).get("status") != "ok":
        print(f"  FAIL  /api/band/40 still blocked after unlock: {b}"); lock_fail += 1
    print(f"  vfo lock:  {len(VFO_LOCK_BLOCKED)} blocked, mode allowed, released "
          f"({'ok' if not lock_fail else str(lock_fail) + ' failure(s)'})")

    absent_fail = 0
    for path in HONEST_ABSENT:
        st, b = get(base, path)
        if st != 200 or not isinstance(b, dict):
            print(f"  FAIL  {path}: {st} - absent features must answer, not 404")
            absent_fail += 1
    print(f"  honest:    {len(HONEST_ABSENT) - absent_fail}/{len(HONEST_ABSENT)} "
          "absent features answer with a reason")

    smoke_fail = 0
    for path in SMOKE + SMOKE_PREFIX:
        status, _ = get(base, path)
        if status != 200:
            print(f"  FAIL  {path}: {status}")
            smoke_fail += 1
    print(f"  smoke:     {len(SMOKE) + len(SMOKE_PREFIX) - smoke_fail}/"
          f"{len(SMOKE) + len(SMOKE_PREFIX)} answered 200")

    get(base, "/api/ptt/off")   # best effort; 404 today, see api.cpp
    total = failures + drive_fail + smoke_fail + keypad_fail + lock_fail + absent_fail
    print(f"\n{total} failure(s)")
    return 1 if total else 0


if __name__ == "__main__":
    sys.exit(main())
